== Summary
//(( The Summary clause shall define without ambiguity the subject of this document and the aspect(s) covered. It shall be succinct so that it can be used as a text for bibliographic purposes. Briefly, it shall contain the key results of the work described in the ER. ))
//(( The summary shall further contain a business value statement that should describe the value of this Engineering Report to improve interoperability, advance location-based technologies or realize innovations. ))
//(( The summary shall contain the key findings in a concise form. A more detailed description of the findings should be in the body of the report. ))
//(( This section shall be between 2-3 paragraphs and not longer than 507 words.))

This OGC Engineering Report (ER) will describe the advancement of an Execution Management System (EMS) to support pre-deployed WPS processes, including those of the Earth System Grid Federation (ESGF). The report introduces climate data, processes and applications into CWL workflows with the intent of advancing: application packaging, deployment and execution in clouds; interoperability of services in federated cyberinfrastructures; geospatial workflows towards standardization. Work presented in this report is a direct continuation of the Earth Observation & Clouds (EOC) thread of Testbed-14, and is expected to be of high relevance to the Earth Observation Process and Application Discovery (EOPAD) task of Testbed-15. This engineering report will describe: relevant work conducted in OGC Testbed-14; ESGF and its compute challenge; adaptations of existing climate processes into workflows; interoperability experiments with ESGF endpoints conforming to a common API.

=== Requirements & Research Motivation

The Thematic Exploitation Platform (TEP) open architecture was advanced in previous testbeds tackled Earth observation data in the context of federated, heterogeneous infrastructures. The main requirements included support for application deployment, execution and chaining, as well as the agreed authentication and authorization mechanisms. All interfaces needed to be agreed upon and standardized so as to achieve the Sponsors (European Space Agency, Natural Resources Canada) interoperability goals.

It was observed by certain testbed participants, observers and stakeholders that the same set of requirements applies to climate data, processes and infrastructure. As such, the U.S. Department of Energy’s (DOE) Office of Biological and Environmental Research (BER) sponsored additional engineering work to advance the Earth System Grid Federation (ESGF) interoperability. The general objectives proposed and presented to ESGF stakeholders are as follows, in order of importance:

* Test common ESGF climate processes and their compute nodes
* Demonstrate Testbed-14 TEP architecture for climate processes and applications
* Advance application packaging, deployment and execution in clouds
* Advance interoperability of services in ESGF federated cyberinfrastructure
* Advance geospatial workflows towards standardization
* Explore use of EO data and processes in support of climate infrastructure
* Facilitate use and exchange of ML systems and learned models

=== Prior-After Comparison

Previous work in OGC testbeds allowed definition of application packages in workflow-enabled environments, and their subsequent deployment and execution on distributed secured infrastructures. Data discoverability was superficially addressed through inclusion of Open Search capabilities to identify and select the appropriate data from catalogs. Applications developed for the occasion included stacking, subsetting, feature detection and index computation, both on optical and SAR data. All these concerns are of particular interest for OGC's Earth Observation Exploitation Platform (EO Ex Platform) Domain Working Group (DWG).

The work described in this ER improves interoperability of workflows with pre-deployed WPS 1.0 and WPS 2.0 processes. It also enables the inclusion of pre-deployed processes adhering to the ESGF Compute Working Team (CWT) API. The workflows proposed in this work includes climate data (CMIP6, statistically downscaled climate scenarios, variables and indexes), climate processes (index computation) and base processes (subsetting, averaging). Three different infrastructures were used for <<TIEs, interoperability experiments>>.

The last two objectives of the ESGF concept, the use of EO in support of climate infrastructures and the integration of ML systems, were only partially and informally addressed in this work. It is expected that work planned and conducted in OGC Testbed-15, as well as in other collaborative innovation projects, will continue to support these efforts and drive future requirements.

=== Recommendations for Future Work
//(( This section should answer the question: What does this ER mean for the Working Group and OGC in general? What aspects shall be addressed next? In any specific order? What actions are necessary? ))
//(( This is a write up for why this ER should be important to the working group and OGC. This paragraph provides recommendations on how to further proceed with the achievements documented in this ER. ))

This section presents recommended potential future tasks and deliverables that can support advancement of requirements and expand research motivations. The reader can also refer to Section 9 of this Engineering Report for discussion and open issues for further details.

==== Recommended Future Tasks

. Common architecture for climate and EO infrastructures
. Machine Learning systems and models interoperability

==== Recommended Future Deliverables

===== Recommended Future Components

The following components are suggested to be deployed for testing, demonstration and integration purposes. The resulting functionalities of these components could support both recommended future tasks.

. ESGF Application Profile
. Open Search enabled catalog for climate data
. Clients that can support both EO and climate data
. ML models for detection and localization of extreme climate events
. ML systems supporting interfaces for interoperable DL models, where trained models from a ML system can be loaded into a different one to be used for inference
. ML-enabled application packages and workflows, where a packaged ML system is used in conjunction with pre-processing steps
. Advanced clients to provide user feedback on all previously mentioned future components

===== Recommended Future Engineering Reports (ER)

The following Engineering Reports are suggested to support and document experiments conducted inside previously mentioned recommended future tasks and components.

. EO and climate federated infrastructures ER
. Climate data and processes best practices ER
. Geospatial ML systems best practices ER

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

*Contacts*
[width="80%",options="header",caption=""]
|====================
|Name |Organization
|Tom Landry | CRIM
|David Byrns | CRIM
|David Caron | CRIM
|Francis Charette-Migneault | CRIM
|====================

===	Acknowledgements

Besides this testbed activity participants and observers, the following institutions collaborated in ESGF Compute Challenge and coordinated their efforts:

*	Centro Euro-Mediterraneo sui Cambiamenti Climatici (CMCC)
* Centre Européen de Recherche et de Formation Avancée en Calcul Scientifique (CERFACS)
* Deutsches Klimarechenzentrum (DKRZ)
* Lawrence Livermore National Laboratory (LLNL)
* NASA Center for Climate Simulation (NASA NCCS)
* Ouranos
* University of Utah

// *****************************************************************************
// Editors please do not change the Foreword.
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
