== Terms and definitions

For the purposes of this report, the definitions specified in Clause 4 of the OWS Common Implementation Standard https://portal.opengeospatial.org/files/?artifact_id=38867&version=2[OGC 06-121r9] shall apply. In addition, the following terms and definitions apply.

* AIMS (Analytics and Informatics Management Systems)

// ESGF Face to Face report 2017
Program at LLNL enabling data discovery and knowledge integration across the scientific climate community. (https://aims.llnl.gov/[AIMS])

* CDAT (Community Data Analysis Tools)

CDAT is a powerful and complete front-end to a rich set of visual-data exploration and analysis capabilities well suited for data analysis problems. (https://cdat.llnl.gov/[CDAT])

* CDMS (Climate Data Management System)

// ESGF Face to Face report 2017
Object-oriented data management system specialized in organizing multidimensional gridded data used in climate analyses for data observation and simulation. (https://cdat.llnl.gov/documentation/cdms/cdms.html[CDMS])

* CMIP

// ESGF Face to Face report 2017
Sponsored by the World Climate Research Programme’s Working Group on Coupled Modeling, CMIP is a community-based infrastructure for climate model diagnosis, validation, intercomparison, documentation, and data access. (https://www.wcrp-climate.org/wgcm-cmip[CMIP])

* CORDEX

// ESGF Face to Face report 2017
Provides global coordination of regional climate downscaling for improved regional climate change adaptation and impact assessment. (http://www.cordex.org/[CORDEX])

* CREATE (Collaborative REAnalysis Technical Environment)

// ESGF Face to Face report 2017
NASA project that centralizes numerous global reanalysis data sets into a single advanced data analytics platform. (https://cds.nccs.nasa.gov/tools-services/create/[CREATE])

* Controlled vocabulary

//Wikipedia
Controlled vocabularies provide a way to organize knowledge for subsequent retrieval. They are used in subject indexing schemes, subject headings, thesauri, taxonomies and other forms of knowledge organization systems.

* Dask

Dask is a flexible library for parallel computing in Python. It offers dynamic task scheduling optimized for computation and “Big Data” collections. (https://dask.org/[Dask])

* Deep learning

//Wikipedia
Deep learning is a class of machine learning algorithms that: use a cascade of multiple layers of nonlinear processing units for feature extraction and transformation; learn in supervised and/or unsupervised manners; learn multiple levels of representations that correspond to different levels of abstraction.

 * Deep neural network

//Wikipedia
A deep neural network (DNN) is an artificial neural network (ANN) with multiple layers between the input and output layers. See Artificial Neural Network.

* Downscaling

A method that can provide climate model outputs at a finer resolution than their original resolution. Two different approaches are prioritized: statistical downscaling and dynamical downscaling.

* EDAS (Earth Data Analytics Service)

Developed by NASA NCCS, EDAS is a high-performance big data analytics framework built on Dask/xarray. It allows researchers to leverage computing power to analyze large datasets located at the NCCS through a web-based interface, thereby eliminating the need to download the data. https://www.nccs.nasa.gov/services/analytics/EDAS[EDAS]

* HDF (Hierarchical Data Format)

// ESGF Face to Face report 2017
Data model, library, and file format for storing and managing a wide variety of high-volume and complex data types

* Index (climate index)

Term used to refer to climate properties that are not measured in the field or calculated by climate models but rather that are calculated or derived from climate variables such as temperature and precipitation. Examples include the number of growing degree-days, freeze-thaw cycles, and the drought code index. (see variable)

* IS-ENES (Infrastructure for the European Network for Earth System Modeling)

// ESGF Face to Face report 2017
IS-ENES3 is the third phase project of the distributed e-infrastructure of models, model data and metadata of the European Network for Earth System Modelling. (https://is.enes.org/[IS-ENES3]).

* netCDF (Network Common Data Form)

// ESGF Face to Face report 2017
Machine-independent, self-describing binary data format (unidata.ucar.edu/software/netcdf/).

* OpenAPI

The OpenAPIsSpecification is an API description format for REST APIs.

* OPeNDAP (Open-Source Project for a Network Data Access Protocol)

// ESGF Face to Face report 2017
Architecture for data transport including standards for encapsulating structured data and describing data attributes (opendap.org).

* Obs4MIPs (Observations for Model Intercomparisons)

// ESGF Face to Face report 2017
Database used by the CMIP modeling community to compare satellite observations with climate model predictions. (https://esgf-node.llnl.gov/projects/obs4mips/[obs4mips])

* Profile

//http://docs.opengeospatial.org/per/17-040.html#_terms_and_definitions
Set of one or more base standards and - where applicable - the identification of chosen clauses, classes, subsets, options and parameters of those base standards that are necessary for accomplishing a particular function [ISO 19101, ISO 19106].

* STRATUS (Synchronization Technology Relating Analytic Transparently Unified Services)

NASA project offering an integrative framework presenting a unified API and workflow orchestration for varied climate data analytic services.

* Supervised Learning

//Wikipedia
Supervised learning is the machine learning task of learning a function that maps an input to an output based on example input-output pairs. It infers a function from labeled training data consisting of a set of training examples.

* Variable (climate variable)

The term climate variable is used to refer to a variable that can be measured directly in the field (at meteorological stations for example) or that is calculated by climate models. (See Index)

* Xarray

Xarray is an open source project and Python package focused on multi-dimensional arrays. It includes a library of domain-agnostic functions for advanced analytics and visualization with these data structures. (http://xarray.pydata.org/en/stable/[Xarray])

===	Abbreviated terms

* ACL Access Control List
* ADES Application Deployment and Execution Service
* AOI	Area Of Interest
* AP Application Package
* API Application Programming Interface
* BER Biological and Environment Research
* C3S Copernicus Climate Change Service
* CCCS Canadian Center for Climate Services
* CERFACS Centre Européen de Recherche et de Formation Avancée en Calcul Scientifique
* CRIM Computer Research Institute of Montreal
* CWL	Common Workflow Language
* CWT Compute Working Team
* DKRZ Deutsches Klimarechenzentrum
* DOE U.S. Department of Energy
* ECCC Environment and Climate Change Canada
* EMS	Execution Management Service
* EO Earth Observation
* EOC	Earth Observation Clouds
* EP Exploitation Platform
* ER Engineering Report
* ESA	European Space Agency
* ESGF Earth System Grid Federation
* HPC High-Performance Computing
* IdP Identity Provider
* IPCC Intergovernmental Panel on Climate Change
* IT Information Technology
* JSON JavaScript Object Notation
* KNMI Koninklijk Nederlands Meteorologisch Instituut
* LLNL Lawrence Livermore National Laboratory
* MEP	Mission Exploitation Platform
* ML Machine Learning
* NASA National Aeronautics and Space Administration
* NCCS NASA Center for Climate Simulation
* NRCan Natural Resources Canada
* OPeNDAP Open-Source Project for a Network Data Access Protocol
* PAVICS Power Analytics and Visualization for Climate Science
* PCIC Pacific Climate Impacts Consortium
* OWS	OGC Web Services
* REST REpresentational State Transfer
* SWG Software Working Group
* TB Testbed
* TEP	Thematic Exploitation Platform
* TIE	Technology Integration Experiments
* TOI	Time Of Interest
* URI Uniform Resource Identifier
* URL Uniform Resource Locator
* VM Virtual Machine
* WFS Web Feature Service
* WPS	Web Processing Service
