[[Discussion]]
== Discussion
Section 9 opens up the discussion by further elaborating on findings or on raising open issues from the work.

=== Transition from WPS 1.0 to WPS 3.0
Current adoption of WPS 2.0 standard is still very limited. While 52 North implementations such as https://github.com/52North/javaPS/releases/tag/v1.2.0[javaPS] are based on OGC Web Processing Service standard version 2.0, https://pywps.readthedocs.io/en/master/[PyWPS] server is currently only _planning_ support for this version. In the near future, one can expect to see additional WPS 1.0 endpoints and services appear. By enabling support of pre-deployed WPS 1.0 services into a WPS 2.0 workflow environment, the <<Solution, Solution>> presented in this report has the potential to facilitate the   

Maturation of best practices

=== Docker containers and applications
Entry points to application unclear
Mapping between Docker and app/exec

=== Application, process terminology

=== CWL file formats
Can explicitly define formats, needs to select some ontologies
edam stuff, could develop new ones for geo

=== ESGF API Limitations
One big downside of the ESGF WPS versus standard WPS is that the inputs must be explicitly described in the deployment of a process (for standard WPS, the deployment of a process requires only its url).

We could identify a specific set of inputs that we want to support and include them in a shared interface between deployed ESGF processes. That way, the deployment of a process would be much more succinct. The 'DescribeProcess' command would still show all the inputs available

Here are the inputs that would be easy to include in the interface:

* Common domain variables:
** Latitude (min and max)
** Longitude (min and max)
** Time (min and max)
* Variables (datasets urls and variable name)

And these inputs would need to be investigated as to how to implement them:

* Custom domain variables (their name is provided by the user at execution time, not at deploy time)
* Mask
* Axis
* Gridder

=== Metalinks
Application actuelles retournent un output

=== NASA NCCS STRATUS
Below are STRATUS primary requirements, as listed in its https://github.com/nasa-nccs-cds/stratus/blob/master/docs/STRATUS-WhitePaper-1.0.pdf[white paper]:

* Modular Endpoints: Requires a common endpoint API that can be used to wrap any analytic operator and expose it as an instantiation of a singular analytic module interface.
* Modular Layers: Requires a technology-agnostic architectural layer specification adhering to a common API, which can be instantiated using a wide range of applicable technologies.
* A common language: Requires a common request-response language for describing workflows that can be assimilated and understood by all of the architectural layers and endpoints.

=== Applicability to machine learning

It has been shown with the previous workflows that interoperability between WPS 1.0 and ESGF CWT interface can be achieved with the Weaver component. If climate processes could have been available as Docker application during the short project time frame, a workflow composed of all WPS 1.0, ESGF CWT and WPS-T 2.0 interface could have been tested also.

Since there is active works done using machine learning at CRIM and they are increasingly packaged as Docker applications, the next logical step is to start to integrate them into workflows and leverage the capabilities of the Weaver EMS component to execute them. Moreover, the usage of CWL workflows that can mix and match between all these interfaces is more than welcome by allowing reutilization of existing processes and making workflows more powerful.
